service: osha-cron

provider:
  name: aws
  runtime: nodejs21
  region: us-east-1

functions:
  runCrawler:
    handler: handler.handler
    events:
      - schedule:
          rate: cron(0 2 * * ? *)
          enabled: true

package:
  individually: true
  patterns:
    - handler.js
    - crawler.js
    - '!node_modules/**'
    - '!test/**'
