service: osha-crawler
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    MONGODB_URI: ${ssm:/mancomm/mongodb-uri~true}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:GetParameter
          Resource: arn:aws:ssm:${aws:region}:${aws:accountId}:parameter/mancomm/*
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: arn:aws:logs:${aws:region}:${aws:accountId}:log-group:/aws/lambda/*:*:*

functions:
  crawler:
    handler: src/crawler/handler.handler
    events:
      - schedule: cron(0 12 * * ? *) # Daily at 7AM EST
    timeout: 300
    memorySize: 1024

  getLetters:
    handler: src/api/get-letters.handler
    events:
      - http:
          path: letters
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                page: false
                limit: false
                fromDate: false
                toDate: false

plugins:
  - serverless-plugin-optimize

package:
  patterns:
    - "!node_modules/**/.cache"
    - "!node_modules/aws-sdk/**"
    - "!node_modules/@crawlee/**/test/**"
